# -*- coding: utf-8 -*-
"""0Final_CNN_Pedestrian_detection_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187BGZKWc_lQwY8BvsS3agsSEpy3RwR4f

## 1. IMPORTS AND SETUP
"""

# COMPLETE PYTORCH PEDESTRIAN CLASSIFICATION PIPELINE

## 1. IMPORTS AND SETUP
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import os
from google.colab import drive
import numpy as np
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Mount Google Drive (Colab only)
drive.mount('/content/drive', force_remount=True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

"""##2. DATASET LOADING AND SPLITTING"""

# Dataset path - adjust if your folder structure differs
DATA_PATH = '/content/drive/MyDrive/Detasets_Project'  # Contains "No Pedestrian", "Pedestrian", "Test"

# Data transforms with augmentation for training
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(0.5),
    transforms.RandomRotation(10),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# 1. Load the full dataset without any transforms initially.
# This is to correctly identify class_to_idx and filter out unwanted classes.
initial_full_dataset = datasets.ImageFolder(DATA_PATH)

# Identify the index for the 'Test' class
test_class_index = initial_full_dataset.class_to_idx.get('Test')

if test_class_index is not None:
    # Filter out samples belonging to the 'Test' class from the initial dataset
    valid_indices = [i for i, (_, label) in enumerate(initial_full_dataset.samples) if label != test_class_index]

    # Create two ImageFolder instances with their respective transforms for the entire dataset
    dataset_with_train_transform = datasets.ImageFolder(DATA_PATH, transform=train_transform)
    dataset_with_val_transform = datasets.ImageFolder(DATA_PATH, transform=val_transform)

    # Perform the random split on the indices that correspond to the valid classes, which is 80/20
    train_size = int(0.8 * len(valid_indices))
    val_size = len(valid_indices) - train_size

    g = torch.Generator().manual_seed(42) # for reproducible split
    # random_split operates on indices, so we split range(len(valid_indices))
    train_split_relative_indices, val_split_relative_indices = random_split(range(len(valid_indices)), [train_size, val_size], generator=g)

    # Map these relative indices back to the actual indices in the original dataset
    actual_train_indices = [valid_indices[i] for i in train_split_relative_indices.indices]
    actual_val_indices = [valid_indices[i] for i in val_split_relative_indices.indices]

    # Create the final train_dataset and val_dataset using the appropriate transforms and actual indices
    train_dataset = torch.utils.data.Subset(dataset_with_train_transform, actual_train_indices)
    val_dataset = torch.utils.data.Subset(dataset_with_val_transform, actual_val_indices)

    # Determine classes to print, excluding the 'Test' class
    classes_for_output = [c for i, c in enumerate(initial_full_dataset.classes) if i != test_class_index]

else:
    # If 'Test' class not found, proceed with all classes found, ensuring correct transform application
    print("No 'Test' class found or filtering not applied. Proceeding with all classes from DATA_PATH.")

    # Create two ImageFolder instances with their respective transforms for the entire dataset
    dataset_with_train_transform = datasets.ImageFolder(DATA_PATH, transform=train_transform)
    dataset_with_val_transform = datasets.ImageFolder(DATA_PATH, transform=val_transform)

    # Split indices directly from the full range of samples
    total_samples = len(dataset_with_train_transform)
    train_size = int(0.8 * total_samples)
    val_size = total_samples - train_size

    g = torch.Generator().manual_seed(42) # for reproducible split
    all_indices = range(total_samples)
    train_indices_split_obj, val_indices_split_obj = random_split(all_indices, [train_size, val_size], generator=g)

    # Use the split indices to create subsets from the correctly transformed datasets
    train_dataset = torch.utils.data.Subset(dataset_with_train_transform, train_indices_split_obj.indices)
    val_dataset = torch.utils.data.Subset(dataset_with_val_transform, val_indices_split_obj.indices)

    classes_for_output = initial_full_dataset.classes # All classes are valid

print(f"Training samples: {len(train_dataset)}, Validation samples: {len(val_dataset)}")
print(f"Classes used for training/validation: {classes_for_output}")

# Create data loaders
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2)

"""##3. CNN MODEL DEFINITION

"""

class PedestrianCNN(nn.Module):
    """Simple CNN for binary pedestrian classification"""

    def __init__(self):
        super(PedestrianCNN, self).__init__()
        # Convolutional layers
        self.conv1 = nn.Conv2d(3, 32, 3, padding=1)
        self.conv2 = nn.Conv2d(32, 64, 3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, 3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.relu = nn.ReLU(inplace=True)

        # Fully connected layers
        self.dropout = nn.Dropout(0.4)
        self.fc1 = nn.Linear(128 * 28 * 28, 512)
        self.fc2 = nn.Linear(512, 1)

    def forward(self, x):
        # Conv blocks
        x = self.pool(self.relu(self.conv1(x)))
        x = self.pool(self.relu(self.conv2(x)))
        x = self.pool(self.relu(self.conv3(x)))

        # Flatten and FC layers
        x = x.view(-1, 128 * 28 * 28)
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return torch.sigmoid(x)

# Initialize model, loss, optimizer
model = PedestrianCNN().to(device)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)
print(model)

"""##4. TRAINING AND VALIDATION FUNCTIONS

"""

def train_epoch(model, loader, criterion, optimizer):
    """Single training epoch"""
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for images, labels in loader:
        images, labels = images.to(device), labels.float().unsqueeze(1).to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        predicted = (outputs > 0.5).float()
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    return running_loss / len(loader.dataset), correct / total

def validate(model, loader, criterion):
    """Validation epoch"""
    model.eval()
    running_loss, correct, total = 0.0, 0, 0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.float().unsqueeze(1).to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            predicted = (outputs > 0.5).float()
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    return running_loss / len(loader.dataset), correct / total

"""##5. TRAINING LOOP WITH EARLY STOPPING


"""

# Training parameters
num_epochs = 20
best_val_acc = 0.0
patience = 5
patience_counter = 0

train_losses, val_losses = [], []
train_accs = []
val_accs = []

print("Starting training...")
for epoch in range(num_epochs):
    train_loss, train_acc = train_epoch(model, train_loader, criterion, optimizer)
    val_loss, val_acc = validate(model, val_loader, criterion)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f'Epoch {epoch+1:2d}: Train Loss={train_loss:.4f}, Acc={train_acc:.4f} | '
          f'Val Loss={val_loss:.4f}, Acc={val_acc:.4f}')

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), 'best_pedestrian_model.pth')
        patience_counter = 0
        print(f"  -> New best model saved! Val Acc: {val_acc:.4f}")
    else:
        patience_counter += 1

    # Early stopping
    if patience_counter >= patience:
        print("Early stopping triggered!")
        break

print(f"Training complete! Best validation accuracy: {best_val_acc:.4f}")

"""##6. PLOTTING TRAINING CURVES

"""

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Val Loss')
plt.title('Loss Curves')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(train_accs, label='Train Acc')
plt.plot(val_accs, label='Val Acc')
plt.title('Accuracy Curves')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

plt.tight_layout()
plt.savefig('training_curves.png', dpi=300, bbox_inches='tight')
plt.show()

"""##7. EVALUATION AND CONFUSION MATRIX

"""

# Load best model for evaluation
model.load_state_dict(torch.load('best_pedestrian_model.pth'))
model.eval()

# Confusion matrix on validation set
all_preds, all_labels = [], []
label_names = ['No Pedestrian', 'Pedestrian']

with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(device)
        outputs = model(images)
        preds = (outputs > 0.5).cpu().numpy().flatten()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_names, yticklabels=label_names)
plt.title('Confusion Matrix - Validation Set')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.savefig('confusion_matrix.png', dpi=300, bbox_inches='tight')
plt.show()

print("Model saved as 'best_pedestrian_model.pth'")
print("Training plots saved as 'training_curves.png' and 'confusion_matrix.png'")

import os

# Create the directory if it doesn't exist
os.makedirs("models", exist_ok=True)

torch.save(model.state_dict(), "models/best_pedestrian_model.pth")

# Load best model (same class + same device)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = PedestrianCNN().to(device)
model.load_state_dict(torch.load("models/best_pedestrian_model.pth", map_location=device))
model.eval()
print("Best model loaded for testing.")

"""##**8**. Testing the CNN model"""

from torchvision import transforms

test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225]),
])

from PIL import Image # PIT= Python imaging library

def predict_image(image_path, threshold=0.5):
    img = Image.open(image_path).convert("RGB")
    x = test_transform(img).unsqueeze(0).to(device)

    with torch.no_grad():
        prob = model(x).item()   # sigmoid output between 0 and 1

    if prob >= threshold:
        label = "Pedestrian"
        confidence = prob
    else:
        label = "No Pedestrian"
        confidence = 1 - prob

    return label, confidence * 100.0  # percent

import os
import math
import matplotlib.pyplot as plt

TEST_FOLDER = "/content/drive/MyDrive/Detasets_Project/Test"  # source for testing data

image_exts = (".png", ".jpg", ".jpeg", ".bmp", ".gif")

test_images = [
    os.path.join(TEST_FOLDER, f)
    for f in os.listdir(TEST_FOLDER)
    if f.lower().endswith(image_exts)
]

test_images.sort()
print("Found", len(test_images), "test images.")

results = []
for img_path in test_images:
    fname = os.path.basename(img_path)
    label, conf = predict_image(img_path, threshold=0.5)
    results.append((fname, label, conf))
    print(f"{fname:20s} -> {label:12s} ({conf:5.1f} %)")

N = min(8, len(test_images))  # how many to show

if N > 0:
    num_cols = 4
    num_rows = math.ceil(N / num_cols)
    fig, axes = plt.subplots(num_rows, num_cols, figsize=(16, 4 * num_rows))
    axes = axes.flatten()

    for i in range(N):
        img_path = test_images[i]
        img = Image.open(img_path).convert("RGB")
        label, conf = predict_image(img_path, threshold=0.5)

        axes[i].imshow(img)
        axes[i].set_title(f"{label} ({conf:.1f}%)")
        axes[i].axis("off")

    for j in range(N, len(axes)):
        fig.delaxes(axes[j])

    plt.tight_layout()
    plt.show()
else:
    print("No images in test folder.")